config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/option', to: 'users#option'
  get '/picture', to: 'users#picture'
  get    '/login',   to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#twitter'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/microposts/rank', to: 'microposts#rank'
  get '/microposts/anew', to: 'microposts#anew'
  resources :users
  resources :microposts , only: [:new, :show, :create , :destroy ] do
        resources :comments
  end
  resources :comments do
    resources :likes, only: [:create, :destroy]
  end

  # ここからフォロー
  post 'users/:id/follow', to: 'users#follow', as: 'follow'
  delete 'users/:id/unfollow', to: 'users#unfollow', as: 'unfollow'

  get 'users/:id/follow_list',
      to: 'users#follow_list',
      as: 'follow_list'

  get 'users/:id/follower_list',
      to: 'users#follower_list',
      as: 'follower_list'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  mount_uploader :image_name, ImageUploader
  acts_as_follower
  acts_as_followable
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  has_secure_password
  validates :introduction, length: { maximum: 130 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    user_name = auth[:info][:user_name]
    image_url = auth[:info][:image]
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :option, :update, :destroy, :follow, :unfollow]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    # @microposts = Micropost.all.order(created_at: :desc)
    @comments = @user.comments.order(created_at: :desc)
    @likes = Like.where(user_id: @user.id).order(created_at: :desc)
  end

  def picture

  end

  def option
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "プロフィール編集しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "アカウントを削除しました。"
    redirect_to root_url
  end

  def follow
    @user = User.find(params[:id])
    #ログイン中のユーザーで対象のユーザー(@user)をフォローする
    current_user.follow(@user)
    redirect_to user_url(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    #ログイン中のユーザーで対象のユーザー(@user)をフォロー解除する
    current_user.stop_following(@user)
    redirect_to user_url(@user)
  end

  def follow_list
    @user = User.find(params[:id])
    @users = @user.all_following
  end

  def follower_list
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private

    def user_params
        params.require(:user).permit(:name, :email, :introduction, :image_name, :remove_image_name, :password,
                                     :password_confirmation)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1 class="top">ユーザー編集ページ</h1>

<div class="edit" style="text-align:center;">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name, "ユーザー名" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :introduction, "プロフィール" %>
    <%= f.text_area :introduction, class: 'form-control' %>

    <p>プロフィール画像</p>
    <%= f.file_field :image_name, class: 'image-edit' %>

    <p class="image-delete"><%= f.check_box :remove_image_name %> プロフィール画像を削除する</p>

    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "パスワードの確認" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <div class="submit">
      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/follow_list.html.erb
<div class="about">
  <h1><%= @user.name %>さんのフォローリスト</h1>
</div>

<div id="follow_list">
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
  </ul>
</div>

app/views/users/follower_list.html.erb
<div class="about">
  <h1><%= @user.name %>さんのフォロワーリスト</h1>
</div>

<div id="follower_list">
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<h1 class="signup">新規登録</h1>

<div class="signup-can">
  <div class="signup-can-be">
    <h2>アカウント登録するとできる事</h2>
    <p>・テーマを決める</p>
    <p>・テーマ毎にコメント</p>
    <p>・いいね！をつける</p>
  </div>
</div>

<div class="form signupsize" style="text-align:center;">
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>


    <%= f.label :name, "ユーザー名" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "パスワードの確認" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <div class="submit">
      <%= f.submit "アカウントを登録する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/option.html.erb
<div class="signup-can">
  <div class="signup-can-be">
    <h2>オプション</h2>
      <ul class="option">
        <li><%= link_to "プロフィールの編集", edit_user_path(current_user), class: 'option' %></li>
        <li><%= link_to "アカウント削除", current_user, method: :delete,
                                        data: { confirm: "本当に削除しますか？" }, class: 'option' %></li>
      </ul>

  </div>
</div>

app/views/users/show.html.erb
<div class="user-image">
    <% if @user.image_name? %>
      <%= link_to @user.image_name.url, target: "_blank",:rel => "lightbox" do %>
        <%= image_tag @user.image_name.url, :class => "user-image-position" %>
      <% end %>
    <% else %>
        <%= image_tag "default_user.jpg", :class => "user-image-position" %>
    <% end %>
</div>
  <p class="user-name">
    <%= @user.name %>
    <% if current_user?(@user) %>
    <span>
      <%= link_to option_path do %>
        <%= fa_icon 'cog', class: "cog" %>
      <% end %>
    <% end %>
    </span>
  </p>
  <% if logged_in? %>
    <% unless current_user == @user %>
      <div class="follow">
      <% if current_user.following? @user %>
        <p><%= link_to 'フォロー中', unfollow_path(@user), method: :delete, :class => "follow-t" %></p>
      <% else %>
        <p><%= link_to 'フォローする', follow_path(@user), method: :post, :class => "follow-t" %></p>
      <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="followlist">
    <%= link_to "#{@user.follow_count} フォロー",follow_list_path(@user), :class => "following" %>
    <%= link_to "#{@user.followers_count} フォロワー",follower_list_path(@user), :class => "follower" %>
  </div>
  <% if @user.introduction? %>
    <div class="introduction-box">
      <p class="introduction"><%= @user.introduction %></p>
    </div>
  <% end %>

  <div class="user-set">
    <div class="user-set-box">
      <ul class="user-set-list">
        <li class="themes">テーマ</li>
        <li class="comments">コメント</li>
        <li class="likes">いいね</li>
      </ul>
    </div>

  <div class="themes-box">
    <% @user.microposts.each do |micropost| %>
      <div class="block">
        <div class="form-range">
          <%= link_to micropost.user do %>
            <%= image_tag micropost.user.image_name.url, :class => "image" %>
          <% end %>
        </div>
        <div class="form-range-2">
        <p class="name"><%= link_to "#{micropost.user.name}".truncate(15), micropost.user, :class => "name"%></p>
        <p class="time"><%= simple_time(micropost.created_at) %></p>
        <p class="micropost"><%= link_to micropost.content.truncate(30),"/microposts/#{micropost.id}", :class => "micropost" %></p>
        <div class="right">
          <span class="comment"><%= link_to "コメント(#{micropost.comments.count})","/microposts/#{micropost.id}", :class => "comment"%></span>
          <% if micropost.user == current_user %>
            <%= link_to "削除", micropost_path(micropost.id), method: :delete,
                   data: { confirm: "本当に削除しますか?" } %>
          <% end %>
          </div>
        </div>
        <hr />
      </div>
    <% end %>
  </div>


  <div class="comments-box">
    <% @comments.each do |comment| %>
      <div class="block">
        <div class="form-range">
          <%= link_to comment.user do %>
            <%= image_tag comment.user.image_name.url, :class => "image" %>
          <% end %>
        </div>
        <div class="form-range-2">
        <p class="name"><%= link_to "#{comment.user.name}".truncate(15), comment.user, :class => "name"%></p>

        <p class="time"><%= simple_time(comment.created_at) %></p>

        <p class="micropost"><%= link_to comment.body,"/microposts/#{comment.micropost_id}", :class => "micropost"%></p>
        <% if comment.picture? %>
          <%= link_to comment.picture.url, target: "_blank",:rel => "lightbox" do %>
            <%= image_tag comment.picture.url, :class => "picture-size" %>
          <% end %>
        <% end %>
        <div class="right">
          <div id="likes_buttons_<%= comment.id %>">
            <%= render partial: 'likes/like', locals: { comment: comment, likes: @likes} %>
          </div>
        <% if comment.user == current_user %>
          <%= link_to "削除", comment_path(comment.id), method: :delete,
                   data: { confirm: "本当に削除しますか?" } %>
        <% end %>
        </div>
        </div>
        <hr />
      </div>
    <% end %>
  </div>


  <div class="likes-box">
    <% @likes.each do |like|%>
    <% comment = Comment.find_by(id: like.comment_id)%>
      <div class="block">
        <div class="form-range">
          <%= link_to comment.user do %>
            <%= image_tag comment.user.image_name.url, :class => "image" %>
          <% end %>
        </div>
        <div class="form-range-2">
        <p class="name"><%= link_to "#{comment.user.name}".truncate(15), comment.user, :class => "name"%></p>

        <p class="time"><%= simple_time(comment.created_at) %></p>

        <p class="micropost"><%= comment.body.truncate(30)%></p>
        <% if comment.picture? %>
          <p class="click-picture"><<画像>></p>
          <div class="picture-js-box">
            <p class="exit">閉じる</p>
            <div class="picture-js">
              <%= image_tag comment.picture.url, size: "300x300"%>
            </div>
          </div>
        <% end %>
        <div class="right">
        <% if comment.find_like_by(current_user) %>
          <%= link_to comment_like_path(comment, comment.find_like_by(current_user)),
            method: :delete, remote: true do %>
            <%= fa_icon 'heart', class: "fa-pink" %>
          <% end %>
        <% else %>
          <%= link_to comment_likes_path(comment), method: :post, remote: true do %>
            <%= fa_icon 'heart', class: "fa-white" %>
          <% end %>
        <% end %>
        <%= comment.likes.count %>

        <% if comment.user == current_user %>
          <%= link_to "削除", comment_path(comment.id), method: :delete,
                   data: { confirm: "本当に削除しますか?" } %>
        <% end %>
        </div>
        </div>
        <hr />
      </div>
    <% end %>
  </div>

  <script>
    $(function() {
      $('.themes-box').show();
      $('.themes').css('border-bottom', 'solid black');
      $('.comments-box').hide();
      $('.comments').css('border-bottom', '');
      $('.likes-box').hide();
      $('.likes').css('border-bottom', '');
      // 「#hide-text」要素に対するclickイベントを作成してください
      $('.themes').click(function() {
        $('.likes-box').hide();
        $('.comments-box').hide();
        $('.themes-box').show();
        $('.themes').css('border-bottom', 'solid black');
        $('.comments').css('border-bottom', '');
        $('.likes').css('border-bottom', '');
      });
      $('.comments').click(function() {
        $('.likes-box').hide();
        $('.themes-box').hide();
        $('.comments-box').show();
        $('.comments').css('border-bottom', 'solid black');
        $('.themes').css('border-bottom', '');
        $('.likes').css('border-bottom', '');
      });
      $('.likes').click(function() {
        $('.comments-box').hide();
        $('.themes-box').hide();
        $('.likes-box').show();
        $('.likes').css('border-bottom', 'solid black');
        $('.themes').css('border-bottom', '');
        $('.comments').css('border-bottom', '');
      });
    });
  </script>

  <script>
    $(function() {
      $('.picture-js-box').hide();
      $('.click-picture').click(function() {
        $('.picture-js-box').show();
      });
      $('.exit').click(function() {
        $('.picture-js-box').hide();
      });
    });
  </script>