config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/option', to: 'users#option'
  get '/picture', to: 'users#picture'
  get    '/login',   to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#twitter'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/microposts/rank', to: 'microposts#rank'
  get '/microposts/anew', to: 'microposts#anew'
  resources :users
  resources :microposts , only: [:new, :show, :create , :destroy ] do
        resources :comments
  end
  resources :comments do
    resources :likes, only: [:create, :destroy]
  end

  # ここからフォロー
  post 'users/:id/follow', to: 'users#follow', as: 'follow'
  delete 'users/:id/unfollow', to: 'users#unfollow', as: 'unfollow'

  get 'users/:id/follow_list',
      to: 'users#follow_list',
      as: 'follow_list'

  get 'users/:id/follower_list',
      to: 'users#follower_list',
      as: 'follower_list'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeisakuApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
  </head>

  <body>
    <div id="header">
      <%= link_to "『 談話室 』", root_path, class: "logo"%>
      <ul class="header-list">
        <li><%= link_to "新着", "/microposts/anew", :style=>"color:black;" %></li>
        <li><%= link_to "人気", "/microposts/rank", :style=>"color:black;" %></li>
        <% if logged_in? %>
          <li><%= link_to "テーマを作る", new_micropost_path, :style=>"color:black;" %></li>
          <li><%= link_to "マイページ", current_user, :style=>"color:black;" %></li>
          <li><%= link_to "ログアウト", logout_path, method: :delete, :style=>"color:black;" %></li>
        <% else %>
          <li><%= link_to "新規登録", signup_path, :style=>"color:black;"%></li>
          <li><%= link_to "ログイン", login_path, :style=>"color:black;"%></li>
        <% end %>
      </ul>
    </div>

    <% if flash[:notice] %>
      <div class="message notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:danger] %>
      <div class="message danger">
        <%= flash[:danger] %>
      </div>
    <% end %>

    <div class="main">
    <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </body>
</html>